CREATE TABLE "dialer_campaign" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"dial_method" text DEFAULT 'Preview' NOT NULL,
	"disposition_list" text DEFAULT 'CRLAB' NOT NULL,
	"wrap_up_time" integer DEFAULT 30 NOT NULL,
	"refresh_count" integer DEFAULT 1 NOT NULL,
	"after_call_work_duration" integer DEFAULT 0 NOT NULL,
	"preview_duration" integer DEFAULT 10 NOT NULL,
	"campaign_caller_id" text DEFAULT '' NOT NULL,
	"dial_status" text DEFAULT 'New' NOT NULL,
	"refresh_interval" text DEFAULT '00:00:30' NOT NULL,
	"agent_connection_method" text DEFAULT 'Dial In (Session)' NOT NULL,
	"enforce_agent_pause_code" boolean DEFAULT false NOT NULL,
	"agent_dial_in_number" text DEFAULT '' NOT NULL,
	"agent" text DEFAULT '' NOT NULL,
	"ring_timeout" integer DEFAULT 30 NOT NULL,
	"agent_only_callback" boolean DEFAULT false NOT NULL,
	"agent_voice_greeting" text DEFAULT 'Select an option' NOT NULL,
	"caller_id_type" text DEFAULT 'Select an option' NOT NULL,
	"campaign_script" text DEFAULT 'Select an option' NOT NULL,
	"time_group" text DEFAULT 'Select Time Group' NOT NULL,
	"account_timezone" text DEFAULT 'Asia/Kolkata' NOT NULL,
	"add_transfer_list" text DEFAULT 'Select an option' NOT NULL,
	"after_call_disposition" text DEFAULT 'Select an option' NOT NULL,
	"holiday_calendar" text DEFAULT 'Select an option' NOT NULL,
	"enable_manual_dial" boolean DEFAULT false NOT NULL,
	"manual_dial_limit" integer DEFAULT 0 NOT NULL,
	"enable_inbound" boolean DEFAULT false NOT NULL,
	"webform" text DEFAULT 'Select Webform' NOT NULL,
	"calls_before_ring_duration" integer DEFAULT 30 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);