CREATE TABLE "inbound_queue" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"ring_strategy" text DEFAULT 'Random' NOT NULL,
	"agent_ring_time" integer DEFAULT 30 NOT NULL,
	"follow_user_group" text DEFAULT 'Hangup' NOT NULL,
	"sticky_agent" boolean DEFAULT false NOT NULL,
	"sbc_missed_call_caller" text DEFAULT 'Select any Option' NOT NULL,
	"sbc_missed_call_agent" text DEFAULT 'Select any Option' NOT NULL,
	"webhook_missed_call_caller" text DEFAULT 'Select any Option' NOT NULL,
	"webhook_missed_call_agent" text DEFAULT 'Select any Option' NOT NULL,
	"transfer_code" text DEFAULT '' NOT NULL,
	"wait_announcement" boolean DEFAULT false NOT NULL,
	"position_announcement" boolean DEFAULT false NOT NULL,
	"queue_timeout" integer DEFAULT 90 NOT NULL,
	"music_on_hold" text DEFAULT 'Select any Option' NOT NULL,
	"follow_me" text DEFAULT 'Select any Option' NOT NULL,
	"enable_repeat_caller" boolean DEFAULT false NOT NULL,
	"pbxconfig_id" text DEFAULT '' NOT NULL,
	"welcome_announcement" text DEFAULT 'Select any Option' NOT NULL,
	"enable_queue_url" boolean DEFAULT false NOT NULL,
	"agent" text DEFAULT '' NOT NULL,
	"agent_priority" boolean DEFAULT false NOT NULL,
	"sla_duration" integer DEFAULT 0 NOT NULL,
	"callback_crossover" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);